{% set version = "1.5-18" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geosphere
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geosphere_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geosphere/geosphere_{{ version }}.tar.gz
  sha256: 99ff6ff050cc8c2d565b6bb1488607fc7950a6d448930f8d9642eccefbc6dac0

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-sp                       # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-sp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-sp

test:
  commands:
    - $R -e "library('geosphere')"           # [not win]
    - "\"%R%\" -e \"library('geosphere')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=geosphere
  dev_url: https://github.com/rspatial/geosphere
  doc_url: https://rspatial.org/raster/sphere/index.html
  license: GPL-3.0-or-later
  summary: 'Spherical trigonometry for geographic applications. That is, compute distances and related measures for angular (longitude/latitude) locations. '
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - ConorIA
    - conda-forge/r
