travis:
  secure:
    BINSTAR_TOKEN: ciPeAJP7k2Tr0aPTLUUQMS0qdoMzhOoVIkrvGPLH+TYfY16mmTvyJe6ZjAqZSVT9AO/VrW+AM1jXtDIGqLhjqNc2v/+o2wmJaeOLaaLb9I87eLQZ3oAMNLBkTDzUyA33A1v6ahIfO3TI7N2ypyxBqJzxvABM//XaXtKwvScfNKYqwxBV2GBxUVrSge3YTvYs14xtus3fUlc5pRHrC7jMPf/l2oh5Zrr95TzjElc4ES5exhqdTjB5FmxRLIRvbgh/BjVt0Lee2Sjwryr5iMYd+5XW8fyY3gJ4Ci3GvQjoxs6g6Tyms1UE87lRYi4DZL/2+j9rL6FT288asuBzyiICjneCjpcOf//QA6kzllPUXrn2cRmlfipYfqra2dM3r1zfE7h60VVa0eLFIfGdV4rOhB681KZaWxmH6MJ+OqblNfJeAOCedwGmj6OmjJr8y4egghN6oH5G9kSgmbAlUVSj3xnsfy1k0D57JLtiOlNbABjQUd8/4YNkSyj0xahi0VAvihg8gzFVYjuAz2Tb29ziQR5pM+MEtMpqHcEpAv9RFAFzk35wrNQ3Iz1ubWHVuAGuYDjFzbWQPzOPoWapHJ6unh86f/83J1UTkQggefmiI7RL5pyYnmIY1iSb1d3YLwHeaD7VS0oaWtqTymvdaOFblbLbxaJA+v+UCnEdCbK5DCo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
