travis:
  secure:
    BINSTAR_TOKEN: KikdpF0lr77bs13VpQ2PapT4n4Ympny+4gIRWyQEHHfwrY5B5KQIBxZBymT4Xur+w0egRosQchvnvhuL4HOejyFBy4mtCmpEOX/l8gSD/jaT7KjZvym06Ms40DWPFngQ2nAiDVwj6t0hc+g8ajf/f6eLTLEQK6eJ6WDJ7iGlEysq2zwaOlSllygBUL1TCcB44W7GjOfs7PBRUogGy7gdiVv+UAT9qc4eql0Hr2NwbWJxRG2wQd9FzHeSRPbw1kCRPcBRlzKr+vSBY/2+XfhKeyfM8vtje1Tj2lbaHzIQRPABnIt4SXtTaJU5dlfOh1DJvO8lup4PJW0HnZtqspjOyZZK18KEHf9na9vll5QLwvhDThBwjUeItvUzt0maziIUoyvOpedDwgnIRD4c1Kq46Uk6PVipk0GPEYBFpnD/OBTX66mQW7PcCzuYBehRQXvBDILrc2R0i+oEfDsTyQviVaGBAZGzQKrdESYjZKEaE55oadH9hH8D5Y7+Q1ouHH8xCF7wx70W37Ku5u/n53Tx09cNHOGZ9+0SFg40EjgVrLziZd4Onep1+liXz85SgBnNRE83oUifj17lVVlk7NxMaf+l7rqTj1qZ4b3kBPcyQAk+LJuRkcfM4XpjH+G1cFTyDGxVkadYla1orPK4VWaY0NZwgF45Lz8PhF9g2Vg8oSo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
