appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: P7lWxM2UzmBCvZ38f9NfwikegLO+iOwXibLIGqKExGpIrfK6IZtHYQrwB6rUxwtNJXhQYUNE9iJJdQZirsMiXXdLGBcwxOeradqM8PHq0LXU0dijePFL3xKXadU9WM6NzhBwd7r9Tds5Jy57BdjLefEGy4YII1BBU6gIhTr/FMXtMNgqSMJFdlOgOaiq8xzUzHk9h7LTM9aJtH1IQXcFDAgjskAc/YT7iK5VMPPlcdrkAzZhmvL6lM8RFYf7bnJdJqy9T1rq1KqbNncQcMfjb0JY8VRW+QAnRRLj1LdeAWK14Vk4s/M/kQ0FenzreZx0a1PPqzV8mtSEaW10P5Wfz6u7nkIkDnwDcCBD7iiK0q6pZ8H3pL9YaokdbaUobreKz2giJBR6o6sfyWfey9mUG/i+ct6CU6kKX2Kx3+71Wo1tDuhRIDsmeSolVEkvv4pu2pvzrSvspkLFrhjLVo7VSuXi6qS9sEjWYZlRT6egY2f6BQkeGGyHCs89q6RWu/a8vCsbwWs+ErnaSptlaXBIzEDLdGDJAioHyraHXWLYhVUv9+SaGQvIzcW7BQHm4T91fF4AfPYUHvqAbp/xR1wNusfrbP16ppxWdNf7dWo2ungpVcT70nc+KjZLxoAQ3tY25VwMfOSTSHM2m3wzZc95waonoSlWa9gws5Q1yyg6k5A=}
