travis:
  secure:
    BINSTAR_TOKEN: VEQXsuGFU3ajg23uChph87WUZxf+AZ0nwFmoT5RigEzbGIY0guWGHhgYf7+BCs+1LNTpFLTa5wGFdv2bUDxIoHoK35ijHQSMKeqHU7x4+JJXzZSfUK8nJORrYjUPRvTMWg18gRMkLjdoAkst+DJWTqOLz5C0TMAkrwvLRwNtUI23piIJq+UkODOnbo00TiPoVT1+qxyEXSjfWdv5Ys18aBYNq0ZSt8aRFFrs4Upj4QYj+OZbPgghhvYBu4JcJiUSQe0KufucIPlV5Q4H7+YzOXAWBG2hIkUL24n3e23BD3N65yf2SFhneYHdG+H+x4u57AajGV169peAQA9qlDbAiE0fv0BeAlqQCDwhfWHfonX34iIkyQOsId5WBVZzK1LqtpgPqD5DZutmFdja7+hRTXY2TO9VM8VsSOPe7AQglCE8j+mW16x8aFNQF8k1Dfq+M0vT0JOYZ2LLI3jvEaGlN+KBJsNRAKhJuIZBbsPf3KXGXUbaGKerDUneuriB1bFh4pLBKy+hvRcrvDeYrOUY+4E9Z1YKfbIdk7bBt+LImsBOUxJl16ukmPXbnfjZdUIwyff0w7ujFkRsjtaSIRL+fd1IRUNL6gruAxH0o9ts4QdVZX43stUL1WupoBajclX2G6+TSibZFWnE/2gGONgJhMujS9/5Q9doWfhqhu4e2JU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
