travis:
  secure:
    BINSTAR_TOKEN: FrOcFBze1pDY+b1dkxeW1IlIT6FKT6V9cOBgonGyZ+UZnAZI+muPe9H0NDv+1LxjdWcXeW55BkrSPyAh1kl7dpTmf0uZ9PhZFMKxBvf4G6zdz/Z539NLmdLWW/QlFaVNv4QbSzSNpEn9yR/gbtmGLqm6/PVsGNKs86r7ufv1zoWVSlG8tIfzs4am+brftCpKQj2cxqFHIFJQx5N4PCRgWlB2bQ9g9EbBIYwhYgbCkcKLTWX7CDpXksACFSCHyvRbov1a4vGWG9ZtwsKIGPiWLyfru229gOfeyg1VwuYXICMWpywxKCQ/+2obJZeV8kBnsEpq9u6cv5548OD/uwGsqDSk/zQ+b+oy9RC0e028C6937ou4ddgk2CtMCd36eTlbKcnd3D+Hs6TSlVu8F3RlvmW23xbmtIeMmAwKLy3+wKbBaLvCqzWwwNG3iDoYh9Fre4ChcOv0h0Yk0qPY48t7Ar4OMDdd2WBNDmn5LDGcGm5wgtLkRcM5mmFfASs2Xr9XjvIiQXZAKehB3c5zkzSGz8zK9con8Lrj/WqhPIZrGHuG8LQDPR8JWFFW+03rj2d5lSfuZ7j//p4xeIP+K5PKxig+z3z3FIf64oqkF9pMHeVkLrJfwo7p33hatXU1MwpboH3/EvWOIyXYvsmfYTs9eyNYLZggBxJXMEB4DKLFvQA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
